
pub enum aom_codec_err_t {
    AOM_CODEC_OK,
    AOM_CODEC_ERROR,
    AOM_CODEC_MEM_ERROR,
    AOM_CODEC_ABI_MISMATCH,
    AOM_CODEC_INCAPABLE,
    AOM_CODEC_UNSUP_BITSTREAM,
    AOM_CODEC_UNSUP_FEATURE,
    AOM_CODEC_CORRUPT_FRAME,
    AOM_CODEC_INVALID_PARAM,
    AOM_CODEC_LIST_END,
}
